# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/engtagger.rb'

Hoe.new('EngTagger', EngTagger::VERSION) do |p|
  p.name = "engtagger"
  p.author = "Yoichiro Hasebe"
  p.description = p.paragraphs_of('README.txt', 3).join("\n\n")
  p.email = 'yohasebe@gmail.com'
  p.summary = p.paragraphs_of('README.txt', 1).join("\n\n")
  p.url = "http://engtagger.rubyforge.org"
  p.remote_rdoc_dir = '' # Release to root
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
  p.extra_deps << ['hpricot']
  p.rdoc_pattern = /^(.+\.rb|.+\.txt|.+\.yaml|[^\.]+)$/
  p.need_zip = true
end

desc "Release and publish documentation"
task :repubdoc => [:release, :publish_docs]

# vim: syntax=Ruby
